- name: 'Ansible Test'
  hosts: pan
  connection: local
  gather_facts: true
  collections:
    - paloaltonetworks.panos
  tasks:
    - name: Add tag to address object
      panos_address_object:
        provider: '{{ device }}'
        name: host_192.168.20.51
        address_type: ip-netmask
        value: '192.168.20.51'
        tag: ['openai']
    - name: Commit candidate configs on firewall
      panos_commit_firewall:
        provider: '{{ device }}'

  vars:
    device:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'

